### ISSUE TITLE
package info.freelibrary.vertx.s3 does not exist

### ISSUE THREAD

**Issue by leonidas4321** [ksclarke/vertx-s3-service#34]
download version 1.2.1 and compile it with java 8 and when building it appears package info.freelibrary.vertx.s3 does not exist

**Comment by ksclarke** [comment]
Hi, when you say download do you mean from the GitHub "Releases" page? It looks like 1.2.1 has that package to me (inside the standard Maven src/main/java): /vertx-s3-service-vertx-super-s3-1.2.1/src/main/java/info/freelibrary/vertx/s3/

You'll need Maven to compile it since it uses that as its project management tool (and the directory structure uses Maven's conventional locations).

The bigger problem may be with Java 8 though. The code uses classes from Java 11 so I don't think you'll be able to use with JDK 8. I should add a note about that to the README.

**Comment by ksclarke** [comment]
Closing since no additional details were provided.
